#!/usr/bin/env python3
"""Build data/geo/geometry_us_saus.js from the USGS 2013 National Assessment.

Geometry: SAU polygons queried live from the USGS ArcGIS REST StudyAreas
services (energy.usgs.gov, public domain). Capacity: DS774 Table 1
(Technically Accessible Storage Resource, Mt CO2, P5/P50/P95/Mean) joined
by SAU code. Replaces the NATCARB 10-km-grid saline layer, which is the
structural cause of the blocky US formation outlines.

Usage: python3 scripts/build_us_saus.py [path/to/Table_1.xlsx]
Table_1.xlsx: https://pubs.usgs.gov/ds/774/tables/Table_1.xlsx
"""
import json
import sys
import time
import urllib.request
from pathlib import Path

import openpyxl
from shapely.geometry import shape, mapping

ROOT = Path(__file__).resolve().parent.parent
BASE = "https://energy.usgs.gov/arcgis/rest/services"
UA = {"User-Agent": "Mozilla/5.0 (co2-storage-map build; zeke@berkeleyearth.org)"}
SIMPLIFY_DEG = 0.008
DEC = 3


def get_json(url, retries=3):
    for i in range(retries):
        try:
            req = urllib.request.Request(url, headers=UA)
            with urllib.request.urlopen(req, timeout=60) as r:
                return json.loads(r.read())
        except Exception as e:
            if i == retries - 1:
                raise
            time.sleep(2 * (i + 1))


def load_capacity(xlsx_path):
    wb = openpyxl.load_workbook(xlsx_path, read_only=True)
    ws = wb["Comprehensive Data Table"]
    cap = {}
    for row in ws.iter_rows(min_row=9, values_only=True):
        code = row[0]
        if not code or not str(code).startswith("C") or len(str(code)) != 9:
            continue  # basin-group header rows
        def num(x):
            try:
                return float(x)
            except (TypeError, ValueError):
                return None
        cap[str(code)] = {
            "tasr_p5_mt": num(row[78]), "tasr_p50_mt": num(row[79]),
            "tasr_p95_mt": num(row[80]), "tasr_mean_mt": num(row[81]),
            "depth_ml_ft": num(row[50]),
        }
    return cap


def main():
    xlsx = sys.argv[1] if len(sys.argv) > 1 else "Table_1.xlsx"
    cap = load_capacity(xlsx)
    print(f"capacity table: {len(cap)} SAUs")

    services = [s["name"] for s in get_json(f"{BASE}/StudyAreas?f=json")["services"]
                if s["name"].endswith("_webformat")]
    print(f"{len(services)} basin services")

    feats, missing_cap = [], []
    for svc in services:
        layers = get_json(f"{BASE}/{svc}/MapServer?f=json")["layers"]
        sau_layers = [l for l in layers if l["name"].startswith("SAU_")]
        for l in sau_layers:
            gj = get_json(f"{BASE}/{svc}/MapServer/{l['id']}/query"
                          "?where=1%3D1&outFields=*&f=geojson")
            for f in gj.get("features", []):
                p = {k.lower(): v for k, v in f["properties"].items()}
                code = p.get("sau_code")
                if not code:  # fall back to the layer name, e.g. "SAU_C50340102"
                    code = l["name"].replace("SAU_", "").strip()
                geom = shape(f["geometry"]).simplify(SIMPLIFY_DEG, preserve_topology=True)
                c = cap.get(code)
                if c is None:
                    missing_cap.append(code)
                props = {"sau_code": code, "sau_name": p.get("sau_name"),
                         "basin": p.get("basin"), "system": p.get("system")}
                if c:
                    props.update(c)
                g = mapping(geom)
                g["coordinates"] = round_coords(g["coordinates"])
                feats.append({"type": "Feature", "properties": props, "geometry": g})
        print(f"  {svc.split('/')[-1]}: {len(sau_layers)} SAUs (total {len(feats)})")

    fc = {"type": "FeatureCollection", "features": feats}
    out = ROOT / "data" / "geo" / "geometry_us_saus.js"
    out.write_text("// Generated by build_us_saus.py — USGS 2013 National Assessment "
                   "SAU polygons (public domain) + DS774 Table 1 TASR capacity\n"
                   f"window.GEO_US_SAUS = {json.dumps(fc, separators=(',', ':'))};\n")
    joined = sum(1 for f in feats if "tasr_mean_mt" in f["properties"])
    print(f"wrote {out.name}: {len(feats)} SAU polygons, {joined} with capacity, "
          f"{out.stat().st_size/1e6:.2f} MB")
    if missing_cap:
        print(f"NO CAPACITY MATCH for {len(missing_cap)}: {sorted(set(missing_cap))}")


def round_coords(c):
    if isinstance(c, (float, int)):
        return round(c, DEC)
    return [round_coords(x) for x in c]


if __name__ == "__main__":
    main()
