#!/usr/bin/env python3
"""Bundle research JSON into src/data_bundle.js (window.ATLAS)."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESEARCH = ROOT / "data" / "research"

sed = json.loads((RESEARCH / "sedimentary_capacity.json").read_text())
mc = json.loads((RESEARCH / "mineralization_capacity.json").read_text())
projects = json.loads((RESEARCH / "projects.json").read_text())

op_geo = sum(p.get("capacity_mtpa") or 0 for p in projects
             if p["mechanism"] == "geologic" and p["status"] == "operational")
op_ism = sum(p.get("capacity_mtpa") or 0 for p in projects
             if p["mechanism"] == "mineralization" and p["status"] == "operational")

atlas = {
    "global": {
        "geologic": {**sed["global"],
                     "operational_mtpa": round(op_geo, 2),
                     "n_projects": sum(1 for p in projects if p["mechanism"] == "geologic")},
        "mineralization": {**mc["global"],
                           "operational_mtpa": round(op_ism, 3),
                           "n_projects": sum(1 for p in projects if p["mechanism"] == "mineralization")},
    },
    "regions": sed.get("regions", []),
    "countries": sed["countries"],
    "formations": mc["formations"],
    "projects": projects,
    "meta": {
        "built": "2026-07-13",
        "note": ("Capacity tiers are not comparable: theoretical / effective / practical "
                 "estimates answer different questions. See docs/METHODOLOGY.md."),
    },
}

out = ("// Generated by build_bundle.py\n"
       f"window.ATLAS = {json.dumps(atlas, separators=(',', ':'))};\n")
(ROOT / "src" / "data_bundle.js").write_text(out)
print(f"bundle: {len(atlas['countries'])} countries, {len(atlas['formations'])} formations, "
      f"{len(projects)} projects; operational geologic {op_geo:.1f} Mtpa, ISM {op_ism:.3f} Mtpa")
